apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: ingress-nginx
subjects:
  - name: api_staging
    spec:
      fqdn: api.staging.yourdomain.com
      target: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      noTlsVerify: true

tunnelRef:
  kind: Tunnel
  name: your-cloudflare-tunnel
